name: pdf_scanner
description: Pdf scanner built with flutter.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  edge_detection: ^1.0.9
  flutter:
    sdk: flutter
  flutter_swiper:
    git:
      url: git@github.com:kiatuki/flutter_swiper.git
      ref: master
  path_provider: ^2.0.11
  pdf: ^3.8.1
  printing: ^5.9.1
  r_dotted_line_border: ^0.1.1
  uuid: ^3.0.6

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
